python_tests(
    name="tests",
    sources=[
        "test_*.py",
    ],
    skip_mypy=True,
)

python_test_utils(
    name="test_utils",
    sources=[
        "conftest.py",
    ],
)

resources(
    name="test_resources",
    sources=["README.md"],
)
