repos:
  # Miscellaneous checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "mantium/api/routes/well_known/ai_plugin/.*\\.json$"
      - id: check-toml
      - id: check-json
        exclude: .vscode/.+
      - id: check-yaml
        args: ["--unsafe"]

      - id: pretty-format-json
        args:
          - --no-ensure-ascii
          - --autofix
        exclude: .vscode/.+

  # blue auto-formats python files
  - repo: https://github.com/grantjenks/blue.git
    rev: v0.9.1
    hooks:
      - id: blue
        types: [python]
        args:
          - -l120
          - -tpy39
          - --exclude="(\.pantsd|\.dist|\.vscode|\.mypy_cache)"

  # After blue is done reformatting everything, double check it with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        types: [python]
        args:
          - --max-line-length=120
          - --extend-ignore=E203

  - repo: local
    hooks:
      - id: pants-lint
        name: Pants Linter
        entry: sh -c "pants lint ::"
        language: system
        pass_filenames: false
        always_run: true

      - id: pants-check
        name: Pants Check
        entry: sh -c "pants check ::"
        language: system
        pass_filenames: false
        always_run: true

      - id: pants-test
        name: Pants Test
        entry: sh -c "pants test ::"
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/semgrep/pre-commit
    rev: "v1.82.0"
    hooks:
      - id: semgrep
        # See https://semgrep.dev/explore to select a ruleset and copy its URL
        args:
          [
            "--config",
            "auto",
            "--error",
            "--skip-unknown-extensions",
            "--quiet",
          ]
