services:
  mongodb:
    image: mongo:7.0.12
    container_name: pintech_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example_password
    restart: unless-stopped

volumes:
  mongodb_data:
    name: pintech_mongodb_data
